---
site_name: Openness Score
theme:
  name: readthedocs

extra_css:
  - extra.css

extra_javascript:
  - extra.js

markdown_extensions:
  - mdx_truly_sane_lists

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_signature: true
            show_signature_annotations: true
            separate_signature: true
            docstring_style: numpy
            show_symbol_type_heading: true
            show_symbol_type_toc: true

nav:
  - Home: index.md
  - Methodology: methodology.md
  - Design: design.md
  - API Reference:
    - openness_score: openness_score.md
    - coreboot: coreboot.md
    - uefi: uefi.md
